
version: '3'
services:

  fast_compute_service:
    image: lubosmato/playground_fast_compute_service:latest
    restart: unless-stopped
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"

  image_service:
    image: lubosmato/playground_image_service:latest
    restart: unless-stopped
    depends_on:
      - fast_compute_service
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"

  nginx:
    image: lubosmato/playground_nginx:latest
    restart: unless-stopped
    depends_on:
      - image_service
    networks:
      - mynetwork
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
    ports:
      - '80:80'

networks:
  mynetwork:
    driver: bridge
