# 1. vytvořit builder image
#   1. image node
#   2. nakopírovat frontend
#   3. nainstalovat závislosti
#   4. yarn build 
# 2. vytvořit image z nginx
# 3. nakopírovat dist z builderu
# 4. nakopírovat nginx do /etc/nginx/conf.d/default.conf
