
version: '3'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mydockernetwork

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - mydockernetwork
    ports:
      - '80:80'

networks:
  mydockernetwork:
    driver: bridge
