FROM nginx:latest

COPY ./default.conf /etc/nginx/conf.d/default.conf

# docker build . -t mynginx:latest
# docker network create -d bridge mydockernetwork
# docker run -it -p 80:80 --network=mydockernetwork mynginx:latest
