# 1. vytvořit image z node, tag si zvol podle sebe s odůvodněním
# 2. nakopíruj správné soubory
# 3. nainstaluj závislosti
# 4. urči entrypoint a cmd
# 5. build image
# 6. vytvoř síť typu bridge s názvem 'mydockernetwork'
# 7. spusť image, container má být na síti 'mydockernetwork'
